export const UserActionTypes = {
    GOOGLE_SIGN_IN_START: "GSIGNSTRT",
    SIGN_IN_SUCCESS: "SIGNSUCC",
    SIGN_IN_FAIL: "SIGNFAIL",
    EMAIL_SIGN_IN_START: "ESIGNSTRT",
    CHECK_USER_SESSION: "CHECK_SESSION",
    SIGN_OUT_START: "SIGNOUTSTART",
    SIGN_OUT_SUCCESS: "SIGNOUTSUCC",
    SIGN_OUT_FAIL: "SIGNOUTFAIL",
    SIGN_UP_START: "SIGNUPSTART",
    SIGN_UP_SUCCESS: "SIGNUPSUCC",
    SIGN_UP_FAIL: "SIGNUPFAIL"
}

export default UserActionTypes